import { ImageProp } from "./components/ImageCard";

export const engagementPics: ImageProp[] = [
  {
    id: 1,
    alt: "engagement-1",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-1.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 2,
    alt: "engagement-2",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-2.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 3,
    alt: "engagement-3",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-3.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 4,
    alt: "engagement-4",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-4.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 5,
    alt: "engagement-5",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-5.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 6,
    alt: "engagement-6",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-6.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 7,
    alt: "engagement-7",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-7.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 8,
    alt: "engagement-8",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-8.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 9,
    alt: "engagement-9",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-9.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 10,
    alt: "engagement-10",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-10.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 11,
    alt: "engagement-11",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-11.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 12,
    alt: "engagement-12",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-12.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 13,
    alt: "engagement-13",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-13.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 14,
    alt: "engagement-14",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-14.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 15,
    alt: "engagement-15",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-15.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 16,
    alt: "engagement-16",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-16.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 17,
    alt: "engagement-17",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-17.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 18,
    alt: "engagement-18",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-18.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 19,
    alt: "engagement-19",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-19.jpeg`,
    categoryName: "Engagement",
  },
  {
    id: 20,
    alt: "engagement-20",
    src: `${process.env.S3_CDN_ENDPOINT}/engagement-pics/eng-20.jpeg`,
    categoryName: "Engagement",
  },
];

export const bridalPics: ImageProp[] = [
  {
    id: 1,
    alt: "bridal-1",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-1.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 2,
    alt: "bridal-2",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-2.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 3,
    alt: "bridal-3",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-3.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 4,
    alt: "bridal-4",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-4.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 5,
    alt: "bridal-5",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-5.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 6,
    alt: "bridal-6",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-6.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 7,
    alt: "bridal-7",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-7.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 8,
    alt: "bridal-8",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-8.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 9,
    alt: "bridal-9",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-9.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 10,
    alt: "bridal-10",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-10.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 11,
    alt: "bridal-11",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-11.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 12,
    alt: "bridal-12",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-12.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 13,
    alt: "bridal-13",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-13.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 14,
    alt: "bridal-14",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-14.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 15,
    alt: "bridal-15",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-15.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 16,
    alt: "bridal-16",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-16.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 17,
    alt: "bridal-17",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-17.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 18,
    alt: "bridal-18",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-18.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 19,
    alt: "bridal-19",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-19.jpeg`,
    categoryName: "Bridal",
  },
  {
    id: 20,
    alt: "bridal-20",
    src: `${process.env.S3_CDN_ENDPOINT}/bridal-pics/bridal-20.jpeg`,
    categoryName: "Bridal",
  },
];

export const hairPics: ImageProp[] = [
  {
    id: 1,
    alt: "hair-1",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-1.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 2,
    alt: "hair-2",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-2.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 3,
    alt: "hair-3",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-3.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 4,
    alt: "hair-4",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-4.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 5,
    alt: "hair-5",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-5.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 6,
    alt: "hair-6",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-6.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 7,
    alt: "hair-7",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-7.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 8,
    alt: "hair-8",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-8.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 9,
    alt: "hair-9",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-9.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 10,
    alt: "hair-10",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-10.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 11,
    alt: "hair-11",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-11.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 12,
    alt: "hair-12",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-12.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 13,
    alt: "hair-13",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-13.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 14,
    alt: "hair-14",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-14.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 15,
    alt: "hair-15",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-15.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 16,
    alt: "hair-16",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-16.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 17,
    alt: "hair-17",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-17.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 18,
    alt: "hair-18",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-18.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 19,
    alt: "hair-19",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-19.jpeg`,
    categoryName: "Hair Styles",
  },
  {
    id: 20,
    alt: "hair-20",
    src: `${process.env.S3_CDN_ENDPOINT}/hair-pics/hair-20.jpeg`,
    categoryName: "Hair Styles",
  },
];
